# Generated by Django 5.2.11 on 2026-02-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engineers", "0001_initial"),
        ("lookups", "0001_initial"),
        ("milestones", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField()),
                ("delay_description", models.TextField()),
                ("actions_taken", models.TextField()),
                ("impact_on_schedule", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delay_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delay_logs",
                        to="lookups.delaytype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delay_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delay_logs",
                        to="engineers.engineer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delay Log",
                "verbose_name_plural": "Delay Logs",
                "db_table": "delay_logs",
                "ordering": ["-log_date"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField()),
                ("weather_conditions", models.CharField(max_length=100)),
                ("crew_size", models.PositiveIntegerField()),
                ("equipment_used", models.TextField()),
                ("work_progress_detail", models.TextField()),
                ("area_completed", models.CharField(max_length=200)),
                ("issues_risks", models.TextField(blank=True, null=True)),
                ("next_week_plan", models.TextField()),
                ("is_milestone_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_logs",
                        to="engineers.engineer",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_logs",
                        to="milestones.milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Log",
                "verbose_name_plural": "Weekly Logs",
                "db_table": "weekly_logs",
                "ordering": ["-log_date"],
                "unique_together": {("project", "log_date", "milestone")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyLogPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=300)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "weekly_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="logs.weeklylog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Log Photo",
                "verbose_name_plural": "Weekly Log Photos",
                "db_table": "weekly_log_photos",
            },
        ),
    ]
