# Generated by Django 5.2.11 on 2026-02-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklylog",
            name="log_photo",
            field=models.FileField(blank=True, null=True, upload_to="logs/"),
        ),
        migrations.DeleteModel(
            name="WeeklyLogPhoto",
        ),
    ]
