# Generated by Django 5.2.11 on 2026-02-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_weeklylog_log_photo_delete_weeklylogphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="delaylog",
            name="estimated_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delaylog",
            name="progress_percent",
            field=models.FloatField(default=0),
        ),
    ]
