# Generated by Django 5.2.11 on 2026-02-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_delaylog_estimated_days_delaylog_progress_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delaylog",
            name="estimated_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
