# Generated by Django 5.2.11 on 2026-02-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0004_alter_delaylog_estimated_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="delaylog",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
