# Generated by Django 5.2.11 on 2026-02-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0005_delaylog_is_resolved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delaylog",
            name="is_resolved",
        ),
        migrations.AddField(
            model_name="delaylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONGOING", "Ongoing"),
                    ("CRITICAL", "Critical"),
                    ("RESOLVED", "Resolved"),
                ],
                default="Ongoing",
                max_length=250,
            ),
        ),
    ]
