# Generated by Django 5.2.11 on 2026-02-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="Low",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONGOING", "Ongoing"),
                    ("DELAYED", "Delayed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="Ongoing",
                max_length=10,
            ),
        ),
    ]
