# Generated by Django 5.2.11 on 2026-02-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_priority_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_document",
            field=models.FileField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
