# Generated by Django 5.2.11 on 2026-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_project_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_type",
        ),
        migrations.AddField(
            model_name="project",
            name="project_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(max_length=400),
        ),
    ]
