# Generated by Django 5.2.11 on 2026-02-15 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_project_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contractor_contact_person",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
