# Generated by Django 5.2.11 on 2026-02-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_contractor_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor_contact_person',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('COMING_SOON', 'Coming Soon'), ('ONGOING', 'Ongoing'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ONGOING', max_length=15),
        ),
    ]
