# Generated by Django 5.2.11 on 2026-02-18 06:56

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_contractor_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastProjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.projects.models.past_project_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Past Project Record',
                'verbose_name_plural': 'Past Project Records',
                'db_table': 'past_project_records',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
