# Generated by Django 5.2.11 on 2026-02-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("milestones", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="milestone",
            old_name="planned_end_date",
            new_name="target_date",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="planned_start_date",
        ),
    ]
