# Generated by Django 5.2.11 on 2026-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_rename_planned_end_date_milestone_target_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='target_date',
            new_name='planned_completion_date',
        ),
        migrations.AddField(
            model_name='milestone',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
