# Generated by Django 5.2.11 on 2026-03-15 07:30


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_changed_by'),
        ('engineers', '0002_alter_engineer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='engineers.engineer'),
        ),
    ]
