# Generated by Django 5.2.11 on 2026-02-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractcost',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='measurementbook',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='abstractcost',
            name='contingency_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='abstractcost',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='abstractcost',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='abstractcost',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='material',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='measurementbook',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='abstractcost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='abstractcostitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='abstractcostitem',
            name='unit',
            field=models.CharField(default='m³', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Ordered'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='specification',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='unit',
            field=models.CharField(default='bags', max_length=20),
        ),
        migrations.AlterField(
            model_name='measurementbook',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='breadth',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='height',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='length',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='nos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='unit',
            field=models.CharField(default='m³', max_length=20),
        ),
    ]
