# Generated by Django 5.2.11 on 2026-03-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('', 'None'), ('ENGINEER', 'Engineer'), ('CHAIRPERSON', 'Chairperson'), ('FINANCE', 'Finance')], default='', max_length=15),
        ),
    ]
